name: CI

on:
  push: {branches: [main]}
  pull_request: {branches: [main]}

jobs:
  js_checks:
    name: Code checks
    runs-on: ubuntu-latest
    env: {NODE_ENV: test}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: Install client npm dependencies
        run: npm ci
      - name: Run checks
        run: npm run check
